/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { AuctionStatus, QualityLabel, Rarity, TradeStatus, WalletKind } from '#config/game'

export class AuctionSchema extends BaseModel {
  static $columns = ['bidsCount', 'cardId', 'createdAt', 'currentPrice', 'endsAt', 'id', 'leaderId', 'sellerId', 'settledAt', 'startingPrice', 'status', 'updatedAt', 'userCardId'] as const
  $columns = AuctionSchema.$columns
  @column()
  declare bidsCount: number
  @column()
  declare cardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentPrice: number | null
  @column.dateTime()
  declare endsAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leaderId: number | null
  @column()
  declare sellerId: number
  @column.dateTime()
  declare settledAt: DateTime | null
  @column()
  declare startingPrice: number
  @column()
  declare status: AuctionStatus
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userCardId: number
}

export class BidSchema extends BaseModel {
  static $columns = ['amount', 'auctionId', 'bidderId', 'createdAt', 'id'] as const
  $columns = BidSchema.$columns
  @column()
  declare amount: number
  @column()
  declare auctionId: number
  @column()
  declare bidderId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
}

export class BoosterOpeningSchema extends BaseModel {
  static $columns = ['id', 'openedAt', 'userId'] as const
  $columns = BoosterOpeningSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare userId: number
}

export class CardFavoriteSchema extends BaseModel {
  static $columns = ['cardId', 'createdAt', 'id', 'userId'] as const
  $columns = CardFavoriteSchema.$columns
  @column()
  declare cardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class CardTagSchema extends BaseModel {
  static $columns = ['cardId', 'id', 'tagId'] as const
  $columns = CardTagSchema.$columns
  @column()
  declare cardId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagId: number
}

export class CardSchema extends BaseModel {
  static $columns = ['avgDailyViews', 'createdAt', 'description', 'id', 'lang', 'lengthBytes', 'qualityLabel', 'rarity', 'snapshotAt', 'thumbnailUrl', 'title', 'updatedAt', 'wikiPageId', 'wikiRevisionId'] as const
  $columns = CardSchema.$columns
  @column()
  declare avgDailyViews: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lang: string
  @column()
  declare lengthBytes: number
  @column()
  declare qualityLabel: QualityLabel | null
  @column()
  declare rarity: Rarity
  @column.dateTime()
  declare snapshotAt: DateTime
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wikiPageId: number
  @column()
  declare wikiRevisionId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TradeItemSchema extends BaseModel {
  static $columns = ['cardId', 'id', 'ownerId', 'tradeId', 'userCardId'] as const
  $columns = TradeItemSchema.$columns
  @column()
  declare cardId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerId: number
  @column()
  declare tradeId: number
  @column()
  declare userCardId: number | null
}

export class TradeSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'proposerId', 'recipientId', 'respondedAt', 'status', 'updatedAt'] as const
  $columns = TradeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare proposerId: number
  @column()
  declare recipientId: number
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare status: TradeStatus
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserCardSchema extends BaseModel {
  static $columns = ['boosterOpeningId', 'cardId', 'id', 'obtainedAt', 'userId'] as const
  $columns = UserCardSchema.$columns
  @column()
  declare boosterOpeningId: number | null
  @column()
  declare cardId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare obtainedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['adultConfirmedAt', 'balance', 'boosterRefilledAt', 'boosterStock', 'collectionPublic', 'createdAt', 'dailyBonusClaimedOn', 'email', 'id', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare adultConfirmedAt: DateTime
  @column()
  declare balance: number
  @column.dateTime()
  declare boosterRefilledAt: DateTime
  @column()
  declare boosterStock: number
  @column()
  declare collectionPublic: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dailyBonusClaimedOn: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class WalletTransactionSchema extends BaseModel {
  static $columns = ['amount', 'auctionId', 'balanceAfter', 'cardId', 'createdAt', 'id', 'kind', 'userId'] as const
  $columns = WalletTransactionSchema.$columns
  @column()
  declare amount: number
  @column()
  declare auctionId: number | null
  @column()
  declare balanceAfter: number
  @column()
  declare cardId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: WalletKind
  @column()
  declare userId: number
}
