/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { QualityLabel, Rarity } from '#config/game'

export class BoosterOpeningSchema extends BaseModel {
  static $columns = ['id', 'openedAt', 'userId'] as const
  $columns = BoosterOpeningSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare userId: number
}

export class CardSchema extends BaseModel {
  static $columns = ['attack', 'avgDailyViews', 'createdAt', 'defense', 'description', 'id', 'lang', 'lengthBytes', 'qualityLabel', 'qualityScore', 'rarity', 'snapshotAt', 'thumbnailUrl', 'title', 'updatedAt', 'wikiPageId', 'wikiRevisionId'] as const
  $columns = CardSchema.$columns
  @column()
  declare attack: number
  @column()
  declare avgDailyViews: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defense: number
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lang: string
  @column()
  declare lengthBytes: number
  @column()
  declare qualityLabel: QualityLabel | null
  @column()
  declare qualityScore: number | null
  @column()
  declare rarity: Rarity
  @column.dateTime()
  declare snapshotAt: DateTime
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wikiPageId: number
  @column()
  declare wikiRevisionId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class UserCardSchema extends BaseModel {
  static $columns = ['boosterOpeningId', 'cardId', 'id', 'isFavorite', 'obtainedAt', 'userId'] as const
  $columns = UserCardSchema.$columns
  @column()
  declare boosterOpeningId: number | null
  @column()
  declare cardId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFavorite: boolean
  @column.dateTime()
  declare obtainedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['adultConfirmedAt', 'boosterRefilledAt', 'boosterStock', 'createdAt', 'email', 'id', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare adultConfirmedAt: DateTime
  @column.dateTime()
  declare boosterRefilledAt: DateTime
  @column()
  declare boosterStock: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
